security:
    providers:
        haphpy_user_provider:
            id: haphpy.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            anonymous: ~
            oauth:
                resource_owners:
                    github:   "/login/check-github"
                    twitter:  "/login/check-twitter"
                    facebook: "/login/check-facebook"
                login_path:   /login
                use_forward:  false
                failure_path: /login
                default_target_path: "/#contribute"

                oauth_user_provider:
                    service: haphpy.user_provider
            logout:
                path:   /logout
                target: /

        default:
            anonymous: ~

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
