services:
    haphpy.command.generate_contributions:
        class: AFUP\HaphpyBirthdayBundle\Command\GenerateContributionsCommand
        arguments: [@haphpy.contribution_persister]
        tags:
            -  { name: console.command }
