AFUP\HaphpyBirthdayBundle\Entity\Contribution:
    type: entity
    repositoryClass: AFUP\HaphpyBirthdayBundle\Entity\ContributionRepository
    table: contribution
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        authProvider:
            type:   string
            length: 100
            column: auth_provider
        identifier:
            type:   string
            length: 255
        visibleName:
            type:   string
            length: 255
            column: visible_name
        fileName:
            type:   string
            length: 255
        creditWanted:
            type:   boolean
            column: credit_wanted
        moderationState:
            type:   boolean
            column: moderation_state
            nullable: true
        createdAt:
            type:   datetime
            column: created_at
        modifiedAt:
            type:   datetime
            column: modified_at
