services:
    haphpy.user_provider:
        class: AFUP\HaphpyBirthdayBundle\Model\UserProvider
        arguments: [@session]

    haphpy.form.contribution_converter:
        class: AFUP\HaphpyBirthdayBundle\Form\Converter\ContributionConverter

    haphpy.path_generator:
        class: AFUP\HaphpyBirthdayBundle\Service\PathGenerator
        arguments: ['%contribution_dir%']

    haphpy.contribution_persister:
        class: AFUP\HaphpyBirthdayBundle\Service\ContributionPersister
        arguments: [@doctrine.orm.entity_manager, @haphpy.path_generator]

    haphpy.contribution_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AFUP\HaphpyBirthdayBundle\Entity\Contribution
