---

- name: Creates Contribution Media directory
  file: path=/var/haphpy/contributions state=directory group=www-data mode=0770

- name: Add vagrant user to www-data
  user: name=vagrant groups=www-data append=yes
  #when: vagrant environment @TODO
