---
- hosts: all
  sudo: true
  vars:
    web_server: nginxphp
    servername: haphpy-birthday.dev www.haphpy-birthday.dev 192.168.33.99
    timezone: UTC
  vars_files:
    - vars/mariadb.yml
    - vars/common.yml
    - [ "vars/nginxphp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - php5-cli
    - nginx
    - php5-fpm
    - mariadb
    - composer
    - phpcommon
    - app
